# EMAIL_SENDER
mail.from=YOUR_EMAIL@gmail.com
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.user=YOUR_EMAIL@gmail.com
mail.password=YOUR_PASSWORD
mail.smtp.starttls.enable=true
mail.smtp.auth=true
