package com.pharmacy.utils;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;

public class ConfigEmailUtil {

	private Properties configProps;
	private final File configFile;

	public ConfigEmailUtil() {
		String appPath = PathUtil.getAppPath();
		File rootDir = new File(appPath);
		
		File configDir = new File(rootDir, "config");
		
		if (!configDir.exists())
			configDir.mkdirs();

		configFile = new File(configDir, "smtp.properties");
	}

	public Properties loadProperties() throws IOException {
		configProps = new Properties();

		if (configFile.exists()) {
			try (InputStream input = new FileInputStream(configFile)) {
				configProps.load(input);
			}
		} else {
			try (InputStream input = getClass().getClassLoader().getResourceAsStream("smtp.properties")) {
				if (input != null)
					configProps.load(input);
			}
		}

		return configProps;
	}

	public void saveProperties(String host, String port, String user, String pass) throws IOException {
		if (configProps == null)
			configProps = new Properties();

		configProps.setProperty("mail.smtp.host", host);
		configProps.setProperty("mail.smtp.port", port);
		configProps.setProperty("mail.user", user);
		configProps.setProperty("mail.password", pass);
		configProps.setProperty("mail.smtp.starttls.enable", "true");
		configProps.setProperty("mail.smtp.auth", "true");

		try (OutputStream output = new FileOutputStream(configFile)) {
			configProps.store(output, "SMTP settings - Auto generated by Pharmacy App");
		}
	}
}
